#!/bin/bash

sudo tee /etc/nginx/sites-available/myapp <<EOF
server {
    listen 80;
    server_name cryptnex.tech;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/home/ubuntu/Talkify/myapp.sock;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/myapp /etc/nginx/sites-enabled/
sudo systemctl restart nginx

# Install uWSGI
source venv/bin/activate
uwsgi --ini uwsgi.ini
